# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed5e5de546bc4c7373e16ac06ad53ebaf62e42da527aa274360090f5be609e17b3c925c70466559d541c530b0a54bb05eb5f43fe9c085e80d1201443807fe48b

test:
  secret_key_base: 27f86275060e1a571e689ba0c6869d19bb8024900d3af288b59d7cb1cee7d4bc7d1af97ff1d6c727c29ebfc4bc1be4e06fef4b775cc46217cf6d0859fa7e5cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
